### ISSUE TITLE
Unable to create invoice with BTCPayServer

### ISSUE THREAD

**Issue by kakaska** [btcpayserver/php-bitpay-client#11]
It seems this is a php package related issue

https://github.com/btcpayserver/btcpayserver/issues/596

@NicolasDorier do you have time to take a look what is the problem in the BTCPayServer side?

**Comment by NicolasDorier** [comment]
Can you check if you can replicate with v1.0.3.55 I just released ?

**Comment by kakaska** [comment]
I can confirm, that the invoice creation is working with BTCPayServer  v1.0.3.58
